# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Add MinGW-w64 to PATH
        run: echo PATH=%ProgramData%\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%>>%GITHUB_ENV%
        shell: cmd

      - name: Build and run tests
        run: ./script/build.bat
        shell: cmd

      - uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: build/main.exe
